# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'UTUITestLearning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  # Networking
  pod 'Moya'
  # AutoLayout
  pod 'SnapKit'
  # Lint
  pod 'SwiftLint'

end
